### ISSUE TITLE
eligibility calculation Script

### ISSUE THREAD

**Issue by 7vssv7** [threewatcher/misc-tools#5]
Create a script which will accept inputs as defined by https://www.hdfc.com/home-loan-eligibility-calculator and show output as presented on the web page. 

Design your own input/output names and have a help function which will help Users to use your script.

**Comment by 7vssv7** [comment]
@grvvrmtech I'm testing the script, Looks fine. yet to validate the algorithm 

```
saurabhv@saurabhv-macOS-1 [~/threewatcher/misc-tools] 👍 :misc-tools(master)
$ python eligibility_calculator.py  -i 5 -g 20000 -t 5
YOUR LOAN ELIGIBILITY Rs 423925
YOUR LOAN EMI WILL BE Rs 8000/monthly
saurabhv@saurabhv-macOS-1 [~/threewatcher/misc-tools] 👍 :misc-tools(master)
$ python eligibility_calculator.py  -i 5 -g 200000 -t 5
YOUR LOAN ELIGIBILITY Rs 4239256
YOUR LOAN EMI WILL BE Rs 80000/monthly
saurabhv@saurabhv-macOS-1 [~/threewatcher/misc-tools] 👍 :misc-tools(master)
$ python eligibility_calculator.py  -i 5 -g 200000 -t 5 -o 20000
YOUR LOAN ELIGIBILITY Rs 3815330
YOUR LOAN EMI WILL BE Rs 72000/monthly
saurabhv@saurabhv-macOS-1 [~/threewatcher/misc-tools] 👍 :misc-tools(master)
$ python eligibility_calculator.py  -i 5 -g 200000 -t 5 -o 40000
YOUR LOAN ELIGIBILITY Rs 3391405
YOUR LOAN EMI WILL BE Rs 64000/monthly

```
But if I just run without argument script throws error

```
saurabhv@saurabhv-macOS-1 [~/threewatcher/misc-tools] 👍 :misc-tools(master)
$ python eligibility_calculator.py
Traceback (most recent call last):
  File "eligibility_calculator.py", line 97, in <module>
    monthly_emi=emi_eligibility(args.gross_income, args.other_emi)
  File "eligibility_calculator.py", line 84, in emi_eligibility
    if other_emi > gross_income/2:
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

It should instead land me to help page if I supply incorrect or incomplete argument

**Comment by grvvrmtech** [comment]
fixed this bug and commited in repo

**Comment by 7vssv7** [comment]
Thanks @grvvrmtech , Closing this ticket
